### ISSUE TITLE
或许不是问题

### ISSUE THREAD

**Issue by Nat30** [canisminor1990/sketch-name-organizer#2]
Hi，使用了你的这个插件，觉得挺好用的。
用了一段时间，发现有些不太方便的地方：
1、可以在画板名称前加数字顺序，也应该可以去掉。否则，插入画板，调整画板顺序之后，再一次加数字就非常乱了。
2、或者用户重排画板顺序后，sort一下，名称前缀是覆盖之前的。

谢谢，只是个人一点感受。

**Comment by canisminor1990** [comment]
1. 加数字是可以覆盖之前的
2. without numbers 模式可以提供不加数字只排序的形式
