### ISSUE TITLE
Sort Artboards Without Number: Removes spaces from artboard names.

### ISSUE THREAD

**Issue by Indyandie** [canisminor1990/sketch-name-organizer#3]
![initial](https://user-images.githubusercontent.com/1058837/32803363-ec6fa710-c948-11e7-98b4-86fafa1fa971.png)

![update](https://user-images.githubusercontent.com/1058837/32803376-f72e25c8-c948-11e7-96e3-b0ba0e8d75de.png)

I'd like to keep the artboard names intact. 

Thank you!

**Comment by canisminor1990** [comment]
You can set the format style as `Start Case` or turn off it (the default setting is `CamelCase`)

- CamelCase
```
Foo Bar => FooBar
--for-bar-- => FooBar
__FOO_BAR__ => FooBar
```

- Start Case
```
FooBar => Foo Bar
--for-bar-- => Foo Bar
__FOO_BAR__ => Foo Bar
```
