### ISSUE TITLE
Latest release no longer works

### ISSUE THREAD

**Issue by jms21852** [canisminor1990/sketch-name-organizer#4]
Since the last update, now when I tap the Run button nothing happens. I have closed and reopened Sketch several times.

**Comment by canisminor1990** [comment]
update your sketch version to 49.x

**Comment by jms21852** [comment]
Thanks, however it is already 49.1

**Comment by jms21852** [comment]
(I have 49.1 and the plugin no longer works, that is.) Could I get the older version back, the one that did work?

**Comment by canisminor1990** [comment]
You could download the old version from this [repo releases](https://github.com/canisminor1990/sketch-name-organizer/releases)
